// Random school data that is added to Firestore
// After you've signed in, click the dropdown
// menu in the top right corner and select "Add sample schools"

export const randomData = {
  restaurantNames: [
    "Montgomery High School",
    "Maria Carrillo High School",
    "Piner High School",
    "Santa Rosa High School",
    "Elsie Allen High School",
    "Ridgway High School",
    "Roseland University Prep",
    "Casa Grande High School",
    "Petaluma High School",
    "Analy High School",
    "Healdsburg High School",
    "Windsor High School",
    "Sonoma Valley High School",
    "Cardinal Newman High School",
    "Rincon Valley Middle School",
    "Lawrence Cook Middle School",
    "Hilliard Comstock Middle School",
    "Herbert Slater Middle School",
    "Santa Rosa Middle School",
    "Mountain Shadows Elementary",
    "Proctor Terrace Elementary",
    "Steele Lane Elementary",
    "Binkley Elementary",
    "Hidden Valley Elementary",
    "Bella Vista Elementary",
    "Spring Creek Middle School",
    "Kawana Springs Elementary",
    "Petaluma Junior High",
    "McNear Elementary",
    "McKinley Elementary",
    "Wilson Elementary",
    "Lincoln Elementary",
    "Meadow View Elementary",
    "Grace Brothers Elementary",
    "Bellevue Elementary",
    "JX Wilson Elementary",
    "Roseland Creek Elementary",
    "Rincon Valley Union School",
    "Monte Vista Elementary",
    "Summerfield Waldorf School",
    "Sonoma Academy",
    "Credo High School",
    "Oak Grove Charter School",
    "Sequoia Elementary",
    "Brook Hill Elementary",
    "Madrone Elementary",
    "Matanzas Elementary",
    "Hopper Creek Elementary",
  ],
  restaurantCities: [
    "Santa Rosa",
    "Petaluma",
    "Rohnert Park",
    "Sebastopol",
    "Healdsburg",
    "Windsor",
    "Cotati",
    "Sonoma",
    "Kenwood",
    "Glen Ellen",
    "Forestville",
    "Guerneville",
  ],
  restaurantCategories: [
    "Italian",
    "Chinese",
    "Japanese",
    "Mexican",
    "Indian",
    "Mediterranean",
    "Caribbean",
    "Cajun",
    "German",
    "Russian",
    "Cuban",
    "Organic",
    "Tapas",
  ],
  restaurantReviews: [
    { text: "Excellent school with dedicated teachers and strong academics!", rating: 5 },
    { text: "Great learning environment and supportive staff!", rating: 5 },
    { text: "The curriculum is rigorous and well-structured.", rating: 5 },
    { text: "Amazing teachers who really care about the students.", rating: 5 },
    { text: "A wonderful educational experience for my child!", rating: 5 },
    {
      text: "Outstanding programs and extracurricular activities.",
      rating: 5,
    },
    { text: "Well-maintained facilities and modern classrooms.", rating: 5 },
    { text: "Incredible community involvement and parent engagement.", rating: 5 },
    { text: "Good school with a positive atmosphere.", rating: 4 },
    { text: "Solid academics, would recommend to others.", rating: 4 },
    { text: "Reasonable programs and helpful administration.", rating: 4 },
    { text: "Friendly staff, but some areas could be improved.", rating: 3 },
    { text: "Decent school, but nothing extraordinary.", rating: 3 },
    { text: "Average experience, could be better.", rating: 3 },
    {
      text: "Communication was poor, and resources were limited.",
      rating: 2,
    },
    { text: "Expected more, but left disappointed.", rating: 2 },
    { text: "Underwhelming facilities and outdated programs.", rating: 2 },
    { text: "Disappointing experience overall.", rating: 2 },
    {
      text: "The school failed to meet our expectations, very disappointed.",
      rating: 1,
    },
    {
      text: "Worst school experience we've had so far.",
      rating: 1,
    },
    { text: "Avoid this school, poor administration and resources.", rating: 1 },
    { text: "Unprofessional staff and inadequate facilities.", rating: 1 },
    { text: "Simply outstanding! An exceptional educational institution.", rating: 5 },
    { text: "Couldn't be happier with the quality of education.", rating: 5 },
    { text: "Top-notch academics, worth every penny.", rating: 5 },
    { text: "Highly recommended for families seeking quality education.", rating: 5 },
    { text: "Exquisite programs that challenge and inspire students.", rating: 5 },
    { text: "A gem of a school, excellent in every aspect.", rating: 5 },
    { text: "Excellent variety of courses and activities.", rating: 5 },
    { text: "A fantastic learning environment overall.", rating: 5 },
    {
      text: "The community is wonderful, perfect for our family.",
      rating: 4,
    },
    { text: "Good programs, but communication could be improved.", rating: 4 },
    {
      text: "Pleasantly surprised by the range of opportunities.",
      rating: 4,
    },
    { text: "Well-organized activities and helpful teachers.", rating: 4 },
    { text: "Satisfactory education, suitable for our needs.", rating: 4 },
    { text: "The school was okay, nothing special.", rating: 3 },
    {
      text: "Administration could be better, but academics are fine.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more value for the tuition.", rating: 2 },
    { text: "Mediocre programs and lackluster facilities.", rating: 2 },
    {
      text: "Regret choosing this school, disappointing overall.",
      rating: 2,
    },
    { text: "Not up to par with our expectations.", rating: 2 },
  ],
};
